apiVersion: v1
kind: Secret
metadata:
  name: mlflow-tracking-config
  namespace: mlflow
type: Opaque
stringData:
  backend-store-uri: postgresql+psycopg2://mlflow:mlflow-db-password@mlflow-postgresql.mlflow.svc.cluster.local:5432/mlflow
  artifact-root: s3://mlflow-artifacts
  s3-endpoint: http://mlflow-minio.mlflow.svc.cluster.local:9000
  aws-access-key-id: mlflow-access-key
  aws-secret-access-key: mlflow-secret-key
