apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-postgresql
  namespace: infra-tools
  annotations:
    mlops-course/task: "lesson-8"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Oleksandr-Ho/MLOps.git
    targetRevision: lesson-8
    path: mlops-experiments/argocd/apps/postgres
  destination:
    namespace: mlflow
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
